#!/usr/bin/env python3
"""pr_dod_review.py — mechanical DoD + ACs verdict for open PRs.

When all issues are claimed (DEFER_ACTIVE_CLAIM), a session with no work to
claim reviews OPEN PRs against the 7-dimension Definition of Done (CLAUDE.md)
and the frozen acceptance criteria of the underlying issue, commenting what
remains for the claiming agent.

Subcommands:
  check   Print a verdict JSON to stdout (PR body + referenced issue body).
  --post  Publish the verdict as a PR comment via `gh` (requires `gh` auth).
  selftest Run 13 embedded assertions, exit non-zero on any failure.

Stdlib only. Deterministic. No network except in --post mode (gh).
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from typing import Dict, List, Tuple

# The 7 Definition-of-Done dimensions (CLAUDE.md / SKILL.md).
DOD_DIMENSIONS: List[str] = [
    "implementation",
    "unit_tests",
    "integration_tests",
    "system_tests",
    "regression_tests",
    "perf_benchmark",
    "min_coverage",
]

# Keywords that, when present in a PR body, indicate a dimension is addressed.
DOD_SIGNALS: Dict[str, List[str]] = {
    "implementation": ["## implementação", "implementacao", "the change itself", "## what was implemented"],
    "unit_tests": ["unit", "pytest", "test_", "unittest", "coverage of the new"],
    "integration_tests": ["integration", "against its real collaborators", "no mocks"],
    "system_tests": ["end-to-end", "end to end", "e2e", "cli/api surface"],
    "regression_tests": ["regression", "existing suite still green", "no prior behavior"],
    "perf_benchmark": ["benchmark", "latency", "throughput", "measured number", "perf "],
    "min_coverage": ["coverage", "85%", "branch coverage", "line/branch"],
}


def _norm(text: str) -> str:
    return (text or "").lower()


def verdict_dod(pr_body: str, issue_body: str) -> Dict[str, Dict[str, object]]:
    """Return per-dimension status: addressed / missing + evidence snippet."""
    pr = _norm(pr_body)
    issue = _norm(issue_body)
    out: Dict[str, Dict[str, object]] = {}
    for dim in DOD_DIMENSIONS:
        signals = DOD_SIGNALS.get(dim, [])
        hit = [s for s in signals if s in pr]
        # Issue ACs may also supply the evidence the PR references.
        issue_hit = [s for s in signals if s in issue]
        addressed = bool(hit) or bool(issue_hit)
        out[dim] = {
            "addressed": addressed,
            "evidence": (hit or issue_hit or ["(none)"])[0],
        }
    return out


def unresolved_acs(issue_body: str) -> List[str]:
    """Return issue acceptance-criteria checklist lines still unfilled (- [ ])."""
    lines = (issue_body or "").splitlines()
    open_items: List[str] = []
    for ln in lines:
        m = re.match(r"\s*[-*]\s*\[\s*\]\s*(.*)", ln)
        if m:
            open_items.append(m.group(1).strip())
    return open_items


def build_verdict(pr_body: str, issue_body: str, pr_url: str = "", issue_no: str = "") -> Dict[str, object]:
    dod = verdict_dod(pr_body, issue_body)
    acs = unresolved_acs(issue_body)
    addressed = sum(1 for d in dod.values() if d["addressed"])
    total = len(dod)
    verdict = {
        "schema": "simplicio.pr-dod-review/v1",
        "pr_url": pr_url,
        "issue": issue_no,
        "dod_addressed": f"{addressed}/{total}",
        "dod": dod,
        "unresolved_acceptance_criteria": acs,
        "ready_to_merge": (addressed == total and not acs),
    }
    return verdict


def render_comment(v: Dict[str, object]) -> str:
    dod = v["dod"]  # type: ignore[index]
    lines = ["## PR DoD + ACs Review (mechanical)", ""]
    lines.append(f"DoD addressed: **{v['dod_addressed']}**")
    lines.append("")
    lines.append("| Dimension | Status | Evidence |")
    lines.append("|---|---|---|")
    for dim, d in dod.items():  # type: ignore[union-attr]
        status = "✅" if d["addressed"] else "❌"  # type: ignore[index]
        lines.append(f"| {dim} | {status} | {d['evidence']} |")  # type: ignore[index]
    acs = v["unresolved_acceptance_criteria"]  # type: ignore[index]
    lines.append("")
    if acs:
        lines.append("**Unresolved acceptance criteria:**")
        for a in acs:
            lines.append(f"- [ ] {a}")
    else:
        lines.append("**All acceptance criteria resolved.** ✅")
    lines.append("")
    lines.append("> Generated by `scripts/pr_dod_review.py` — mechanical verdict, not a substitute for human review.")
    return "\n".join(lines)


def _post_comment(pr_url: str, body: str) -> Tuple[bool, str]:
    if not pr_url:
        return False, "no PR url provided"
    # Extract owner/repo/number from url like https://github.com/o/r/pull/123
    m = re.search(r"github\.com/([^/]+)/([^/]+)/pull/(\d+)", pr_url)
    if not m:
        return False, f"cannot parse PR url: {pr_url}"
    owner, repo, num = m.group(1), m.group(2), m.group(3)
    try:
        res = subprocess.run(
            ["gh", "pr", "comment", num, "--repo", f"{owner}/{repo}", "--body", body],
            capture_output=True, text=True, check=False,
        )
        if res.returncode != 0:
            return False, res.stderr.strip() or "gh failed"
        return True, res.stdout.strip()
    except FileNotFoundError:
        return False, "gh not installed"


def _load(path: str) -> str:
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Mechanical DoD+ACs review for open PRs")
    p.add_argument("--pr-body", help="PR body text or path (prefix @ to read a file)")
    p.add_argument("--issue-body", help="Referenced issue body text or path (@file)")
    p.add_argument("--pr-url", default="", help="PR url (for --post)")
    p.add_argument("--issue-no", default="", help="Issue number (for context)")
    p.add_argument("--post", action="store_true", help="Publish verdict as a PR comment via gh")
    p.add_argument("subcommand", nargs="?", default="check", help="check | selftest")
    args = p.parse_args(argv)

    if args.subcommand == "selftest":
        return _selftest()

    pr_body = args.pr_body or ""
    issue_body = args.issue_body or ""
    if pr_body.startswith("@"):
        pr_body = _load(pr_body[1:])
    if issue_body.startswith("@"):
        issue_body = _load(issue_body[1:])

    verdict = build_verdict(pr_body, issue_body, pr_url=args.pr_url, issue_no=args.issue_no)
    if args.post:
        ok, msg = _post_comment(args.pr_url, render_comment(verdict))
        print(json.dumps({"posted": ok, "detail": msg, "verdict": verdict}, indent=2))
        return 0 if ok else 1
    print(json.dumps(verdict, indent=2))
    return 0


def _selftest() -> int:
    """13 embedded assertions. Exit 1 on any failure."""
    failures: List[str] = []
    pr = "## Implementação\nUnit tests via pytest. Integration tests with no mocks. System e2e. Regression: existing suite green. Benchmark latency measured. Coverage 90%."
    issue = "## Acceptance Criteria\n- [x] done one\n- [ ] pending two\n- [ ] pending three"

    # 1-7: each DoD dimension detected
    v = build_verdict(pr, issue)
    for i, dim in enumerate(DOD_DIMENSIONS, start=1):
        if not v["dod"][dim]["addressed"]:  # type: ignore[index]
            failures.append(f"{i}: dimension {dim} not detected as addressed")

    # 8-9: unresolved ACs extraction
    acs = v["unresolved_acceptance_criteria"]  # type: ignore[index]
    if len(acs) != 2:
        failures.append(f"8-9: expected 2 unresolved ACs, got {len(acs)}")
    if "pending two" not in acs:
        failures.append("8: missing 'pending two'")
    if "pending three" not in acs:
        failures.append("9: missing 'pending three'")

    # 10: resolved AC not counted
    if "[x] done one" in acs:
        failures.append("10: resolved AC wrongly counted")

    # 11: ready_to_merge false when ACs open
    if v["ready_to_merge"]:  # type: ignore[index]
        failures.append("11: ready_to_merge should be False with open ACs")

    # 12: fully-addressed PR with no open ACs => ready
    full_pr = pr
    full_issue = "## AC\n- [x] a\n- [x] b"
    v2 = build_verdict(full_pr, full_issue)
    if v2["dod_addressed"] != "7/7":  # type: ignore[index]
        failures.append("12: expected 7/7 addressed")
    if not v2["ready_to_merge"]:  # type: ignore[index]
        failures.append("12b: should be ready when all addressed + no open ACs")

    # 13: render_comment contains table + unresolved list
    cm = render_comment(v)
    if "| Dimension |" not in cm:
        failures.append("13: comment missing DoD table")
    if "- [ ] pending two" not in cm:
        failures.append("13b: comment missing unresolved AC")

    if failures:
        print("SELFTEST FAILURES:")
        for f in failures:
            print(" -", f)
        return 1
    print("selftest: 13/13 passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
